name: Run-Fixes

on:
  pull_request:
    branches: [branch1, branch2]
  

jobs:
  Pipeline-Scan:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.3

      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Package App
        run: |
         pwd;
         ./veracode package -s . --output verascan -a

      - name: SAST Scan
        continue-on-error: true
        env:
         VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
         VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: |
         ./veracode static scan ./verascan/veracode-auto-pack-php-goof-php.zip
      
      - name: Upload SAST issues artifact
        uses: actions/upload-artifact@v4.3.3
        with:
           name: results.json
           path: "./results.json"

  Fix-Flaws:
    needs: Pipeline-Scan
    runs-on: [ubuntu-latest]
    permissions: write-all
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.3


      - name: Upload flaws artifact
        uses: actions/download-artifact@v4
        with:
          name: results.json

      - name: Fix Findings
        uses: veracode/veracode-fix@v1.0.4
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          inputFile: results.json
          language: php
          cwe: 89, 80 # SQL Injection and XSS
          fixType: 'batch'
          debug: false
          prComment: true
          files: 'all'
          codeSuggestion: false
          createPR: true

           